spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3308/${DB_NAME:cours_db}
    username: ${DB_USERNAME:david}
    password: ${DB_PASSWORD:Passer1234@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: cours_service/logs/logs.log

server:
  port: 8083