spring:
  application:
    name: api_gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/v1/users/**,/api/v1/students/**
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses/**,/api/v1/classes**,/api/v1/teaching_assignments**
        - id: program-service
          uri: lb://PROGRAM-SERVICE
          predicates:
            - Path=/api/v1/sectors**,/api/v1/academic-year**,/api/v1/niveaux**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            #allow-credentials: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/school-manag-realm

jwt:
  auth:
    converter:
      resource-id: school-manag-client
      principle-attribute: preferred_username

eureka:
  instance:
    prefer-ip-address: true
  #instance:
    #hostname: localhost
    appname: api_gateway
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8088